### ISSUE TITLE
avedata register crash with cryptic message

### ISSUE THREAD

**Issue by JorisBenschop** [nlesc-ave/ave-rest-service#42]
I tried to follow the instruction but got an uncaught exception
```
root@2f146e18cf3f:/data# avedata register --species 'Solanum Lycopersicum' --genome SL.2.40  --datatype variants /data/VSDA_1032-chr_01.bcf
Traceback (most recent call last):
  File "/opt/conda/envs/ave2/bin/avedata", line 11, in <module>
    load_entry_point('avedata==1.0.0', 'console_scripts', 'avedata')()
  File "/opt/conda/envs/ave2/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/ave2/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/ave2/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/ave2/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/ave2/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/envs/ave2/lib/python3.5/site-packages/avedata-1.0.0-py3.5.egg/avedata/commands.py", line 45, in register
  File "/opt/conda/envs/ave2/lib/python3.5/site-packages/avedata-1.0.0-py3.5.egg/avedata/db.py", line 29, in get_db
  File "/opt/conda/envs/ave2/lib/python3.5/site-packages/avedata-1.0.0-py3.5.egg/avedata/db.py", line 16, in init_db
  File "/opt/conda/envs/ave2/lib/python3.5/site-packages/avedata-1.0.0-py3.5.egg/avedata/db.py", line 10, in connect_db
sqlite3.OperationalError: unable to open database file

```

**Comment by sverhoeven** [comment]
This is a combination of the underlying problem of #43 and that the script is unable to create a database file at `/data/ave.db`. 

Once #43 is solved this error should also disappear. 

Is /data mounted in read only? Which command did you use to start the Docker container?
